config/routes.rb
Rails.application.routes.draw do
  resources :shorteners, except: [:show]



  get '/:short_url', to: 'shorteners#show_link'
  get "shorteners/new_release", to: 'shorteners#new_release'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'shorteners#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/shortener.rb
class Shortener < ApplicationRecord

	validates :long_url, presence: true, allow_blank: false

	has_attached_file :snapshot, default_url: "/images/:style/missing.png"

	validates_attachment :snapshot, allow_blank: true,
    :content_type => { :content_type => ["image/jpg", "image/jpeg", "image/png"] },
    :size => { :in => 0..5000.kilobytes }

	scope :active, -> { self.where('created_at >= ?', 1.hours.ago) }

	scope :inactive, -> { self.where('created_at < ?', 1.hours.ago) }

	before_create :generate_short_url

	# after_create :snapshot_url //because it very slow, so we optimize it and use later

	after_initialize :init

	def self.del_expiration_record
		Shortener.where("expiration < ?", Time.now).destroy_all
	end

	def snapshot_url
    kit   = IMGKit.new(self.long_url, quality: 5, width: 400, height: 500, zoom: 0.4)
    img   = kit.to_img(:png)
    file  = Tempfile.new(["template_#{self.id}", 'png'], 'tmp',
                         :encoding => 'ascii-8bit')
    file.write(img)
    file.flush
    self.snapshot = file
    file.unlink
  end

	private

	def init
		self.num_click ||= 0
	end

	def generate_short_url
		begin
			self.short_url = SecureRandom.hex(4)
		end while Shortener.active.exists?(short_url: self.short_url)
	end


end

app/controllers/application_controller.rb
require 'socket'

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :coerce_json

	def coerce_json
    # Rails converts the following header:
    #
    #   Accept: application/json, text/javascript, */*; q=0.01
    #
    # into text/html. Force it back to json.
    if request.headers[ 'HTTP_ACCEPT' ] =~ /^\s*application\/json/
        request.format = 'json'
    end
	end
  # Simple bijective function
#   Basically encodes any integer into a base(n) string,   where n is
#   ALPHABET.length. Based on pseudocode from
#   http://stackoverflow.com/questions/742013/how-to-code-a-url-
#   shortener/742047#742047
  ALPHABET =
  	"abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789".split(//)
  	# make your own alphabet using:
	# (('a'..'z').to_a + ('A'..'Z').to_a + (0..9).to_a).shuffle.join

  def bijective_encode
  	# from http://refactormycode.com/codes/124-base-62-encoding
  	# with only minor modification
  	# return ALPHABET[0] if i == 0
  	# s = ''
  	# base = ALPHABET.length
  	# while i > 0
  	# 	s << ALPHABET[i.modulo(base)]
  	# 	i /= base
  	# end
  	# s.reverse + SecureRandom.hex(5 - s.length)
  	SecureRandom.hex(4)
  end

  def bijective_decode(s)
  	# based on base2dec() in Tcl translation
  	# ad http://rosetttacode.org/wiki/Non-decimal_radices/Convert#Ruby
  	i = 0
  	base = ALPHABET.length
  	s.each_char { |c| i = i * base + ALPHABET.index(c) }
  	i
  end

  def get_hostname
    ip_address = Socket.ip_address_list.find { |ai| ai.ipv4? && !ai.ipv4_loopback? }.ip_address
    hostname = "http://#{ip_address}:#{request.port}/"
  end
  helper_method :get_hostname
end

app/controllers/shorteners_controller.rb
require 'imgkit'

class ShortenersController < ApplicationController
  before_action :set_shortener, only: [:show, :edit, :update, :destroy]
  
  # GET /shorteners
  # GET /shorteners.json
  def index
    @shorteners = Shortener.active.paginate(page: params[:page], per_page: 30)
  end

  # GET /shorteners/1
  # GET /shorteners/1.json
  def show
  end

  def show_link
    @shortener = Shortener.find_by short_url: params[:short_url]
    @shortener.increment!(:num_click)
    redirect_to @shortener.long_url
    rescue NoMethodError
      render text: "Link not found"
  end

  # GET /shorteners/new
  def new
    @shortener = Shortener.new
  end

  # GET /shorteners/1/edit
  def edit
  end

  # POST /shorteners
  # POST /shorteners.json
  def create
    @shortener = Shortener.new(shortener_params)
    respond_to do |format|
      if @shortener.save
        format.json { head :no_content }
        format.js
        # format.html { redirect_to shorteners_path, notice: 'Shortener was successfully created.' }
      else
        format.html { render :new }
        format.json { render json: @shortener.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shorteners/1
  # PATCH/PUT /shorteners/1.json
  def update
    respond_to do |format|
      if @shortener.update(shortener_params)
        format.html { redirect_to @shortener, notice: 'Shortener was successfully updated.' }
        format.json { render :show, status: :ok, location: @shortener }
      else
        format.html { render :edit }
        format.json { render json: @shortener.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shorteners/1
  # DELETE /shorteners/1.json
  def destroy
    @shortener.destroy
    respond_to do |format|
      format.html { redirect_to shorteners_url, notice: 'Shortener was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shortener
      @shortener = Shortener.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shortener_params
      params.require(:shortener).permit(:title, :long_url, :short_url, :num_click, :snapshot)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shorteners_helper.rb
module ShortenersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shortenerurl</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shorteners/_dialog.html.erb
<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
	<h3 id="myModalLabel">Your short URL</h3>
</div>
<div class="modal-body">
	<%= link_to "#{get_hostname}#{@shortener.short_url}", "#{get_hostname}#{@shortener.short_url}" %>
	<%= image_tag(@shortener.snapshot.url) %>
</div>
<div class="modal-footer">
	<button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
	<button class="btn btn-primary">Save changes</button>
</div>

app/views/shorteners/_form.html.erb
<%= form_for(shortener) do |f| %>
  <% if shortener.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shortener.errors.count, "error") %> prohibited this shortener from being saved:</h2>

      <ul>
      <% shortener.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :long_url %>
    <%= f.text_field :long_url %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shorteners/_shortener.html.erb
<tr id="shortener_<%= shortener.id %>">
  <td data-no-turbolink><%= link_to "#{shortener.long_url}", shortener.long_url %></td>
  <td data-no-turbolink><%= link_to "#{get_hostname}#{shortener.short_url}", "#{get_hostname}#{shortener.short_url}" %></td>
  <td><%= shortener.num_click %></td>
  <td><%= (shortener.created_at + 1.hours).in_time_zone('Hanoi').strftime("at %Y:%m:%d %I:%M%p") %></td>
  <td><%= link_to 'Show', shortener %></td>
  <td><%= link_to 'Edit', edit_shortener_path(shortener) %></td>
  <td><%= link_to 'Destroy', shortener, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/shorteners/create.js.erb
$("#modal-window .modal-content").html("<%= j render 'shorteners/dialog' %>");
$("#modal-window").modal();
$("#shorteners").append('<%= j render (@shortener) %>')

app/views/shorteners/edit.html.erb
<h1>Editing Shortener</h1>

<%= render 'form', shortener: @shortener %>

<%= link_to 'Show', @shortener %> |
<%= link_to 'Back', shorteners_path %>

app/views/shorteners/index.html.erb
<p id="notice"><%= notice %></p>
<div id="modal-window" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <%= yield %>
    </div>
  </div>
</div>
<div class="main">
  <div class="shorten header">
    <div class="constrain">
      <h1>Simplify your links</h1>
      <div class="container row">
        <div class="input-container col-lg-12 col-md-12 col-xs-12">
          <div class="input-group custom-search-form">
            <%= form_for Shortener.new, :html => {:id => "new_short_url",:remote =>true} do |f| %>
              <% if Shortener.new.errors.any? %>
                <div id="error_explanation">
                  <h2><%= pluralize(Shortener.new.errors.count, "error") %> prohibited this shortener from being saved:</h2>

                  <ul>
                  <% Shortener.new.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                  </ul>
                </div>
              <% end %>

              <%= f.text_field :long_url, id: "search", placeholder: "Your original URL here" %>
              <%= f.submit "GO", id: "submit"%>
              
            <% end %> 
          </div><!-- /input-group -->
        </div>
      </div>
    </div>
  </div>


  <div class="shorten content constrain">
    <div class="table-responsive">
      <table class="table table-bordred table-striped">
        <thead>
          <tr>
            <th>Original URL</th>
            <th>Short URL</th>
            <th>All clicks</th>
            <th>Expiration</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody id="shorteners">
          <%= render @shorteners %>
        </tbody>
      </table>
      <%= will_paginate @shorteners %>
    </div>
  </div>
  <div id="shortener-modal" class="modal fade"> </div>
</div>

app/views/shorteners/new.html.erb
<h1>New Shortener</h1>

<div class="container">
	<div class="row">
		<div class="col-lg-12">
      <div class="input-group custom-search-form">
        <%= form_for(@shortener) do |f| %>
				  <% if @shortener.errors.any? %>
				    <div id="error_explanation">
				      <h2><%= pluralize(@shortener.errors.count, "error") %> prohibited this shortener from being saved:</h2>

				      <ul>
				      <% @shortener.errors.full_messages.each do |message| %>
				        <li><%= message %></li>
				      <% end %>
				      </ul>
				    </div>
				  <% end %>

			    <%= f.text_field :long_url, id: "search", placeholder: "Please input your url" %>
			    <%= f.submit "GO", id: "submit"%>
				  
				<% end %>	
      </div><!-- /input-group -->

	    </div>
	</div>
</div>
<%= link_to 'Back', shorteners_path %>

app/views/shorteners/new_release.js.erb
$("#modal-window .modal-content").html("<%= j render 'shorteners/new_release' %>");
$("#modal-window").modal();
/*$(document).ready( function() {
  $("#modal-window").html("<%= escape_javascript(render 'shorteners/new_release') %>");
  $("#modal-window").modal('show');
});*/

app/views/shorteners/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @shortener.title %>
</p>

<p>
  <strong>Long url:</strong>
  <%= @shortener.long_url %>
</p>

<p>
  <strong>Short url:</strong>
  <%= @shortener.short_url %>
</p>

<p>
  <strong>Num click:</strong>
  <%= @shortener.num_click %>
</p>

<%= link_to 'Edit', edit_shortener_path(@shortener) %> |
<%= link_to 'Back', shorteners_path %>